/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "../JuceLibraryCode/JuceHeader.h"
#include "CSVScanner.h"
#include "CSVDecompressor.h"


//==============================================================================
class CSVScannerApplication  : public JUCEApplication
{
public:
    //==============================================================================
    CSVScannerApplication() {}

    const String getApplicationName() override       { return ProjectInfo::projectName; }
    const String getApplicationVersion() override    { return ProjectInfo::versionString; }
    bool moreThanOneInstanceAllowed() override       { return true; }

    //==============================================================================
    void initialise (const String& commandLine) override
    {
#if SCANNER
		CSVScanner scanner(commandLine);
		Result result(scanner.scan());
		if (result.failed())
		{
			AlertWindow::showNativeDialogBox("Scanner", result.getErrorMessage(), false);
		}
#endif

#if DECOMPRESS
		CSVDecompressor decompressor;
		Result result(decompressor.decompress());
		if (result.failed() && result.getErrorMessage().isNotEmpty())
		{
			AlertWindow::showNativeDialogBox("CSV Decompressor", result.getErrorMessage(), false);
		}
		else
		{
			AlertWindow::showNativeDialogBox("CSV Decompressor", "Created " + decompressor.decompressedFile.getFullPathName(), false);
		}
#endif

		quit();
    }

    void shutdown() override
    {
        // Add your application's shutdown code here..
    }

    //==============================================================================
    void systemRequestedQuit() override
    {
        // This is called when the app is being asked to quit: you can ignore this
        // request and let the app carry on running, or call quit() to allow the app to close.
        quit();
    }

    void anotherInstanceStarted (const String& /*commandLine*/) override
    {
        // When another instance of the app is launched while this one is running,
        // this method is invoked, and the commandLine parameter tells you what
        // the other instance's command-line arguments were.
    }
};

//==============================================================================
// This macro generates the main() routine that launches the app.
START_JUCE_APPLICATION (CSVScannerApplication)
